AWSTemplateFormatVersion: '2010-09-09'
Description: Cluster Amazon EMR configurato per applicazioni Apache Spark

Parameters:
  ClusterName:
    Type: String
    Default: SparkEMRCluster
    Description: Nome del cluster EMR
  ReleaseLabel:
    Type: String
    Default: emr-7.13.0
    Description: Versione della release di EMR (es. emr-6.15.0 include Spark 3.4.1)
  MasterInstanceType:
    Type: String
    Default: m6g.xlarge
    Description: Tipo di istanza EC2 per il nodo Master
  CoreInstanceType:
    Type: String
    Default: m6g.xlarge
    Description: Tipo di istanza EC2 per i nodi Core (Worker)
  CoreInstanceCount:
    Type: Number
    Default: 1
    Description: Numero di istanze Core per il calcolo distribuito
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome della chiave SSH per accedere ai nodi (Master e Core)
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID della subnet dove avviare il cluster
  LogUri:
    Type: String
    Default: s3://logs/emr-logs/
    Description: Percorso del bucket S3 per salvare i log di EMR e Spark
  ServiceRole:
    Type: String
    Default: EMR_DefaultRole
    Description: Ruolo IAM per il servizio EMR
  JobFlowRole:
    Type: String
    Default: EMR_EC2_DefaultRole
    Description: Profilo istanza IAM per i nodi EC2

Resources:
  SparkEMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: !Ref ClusterName
      ReleaseLabel: !Ref ReleaseLabel
      VisibleToAllUsers: true
      LogUri: !Ref LogUri
      ServiceRole: !Ref ServiceRole
      JobFlowRole: !Ref JobFlowRole
      # Installiamo Spark e Hadoop come applicazioni di base sul cluster
      Applications:
        - Name: Spark
        - Name: Hadoop
      Instances:
        Ec2KeyName: !Ref KeyName
        Ec2SubnetId: !Ref SubnetId
        # Mantiene il cluster attivo anche quando non ci sono step in esecuzione
        KeepJobFlowAliveWhenNoSteps: true
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref MasterInstanceType
          Name: Master Node
        CoreInstanceGroup:
          InstanceCount: !Ref CoreInstanceCount
          InstanceType: !Ref CoreInstanceType
          Name: Core Nodes
          Market: SPOT
      Tags:
        - Key: Name
          Value: !Ref ClusterName
        - Key: Application
          Value: SparkEngine

Outputs:
  ClusterId:
    Description: L'ID univoco del cluster EMR creato
    Value: !Ref SparkEMRCluster
  MasterPublicDns:
    Description: Il DNS pubblico del nodo Master
    Value: !GetAtt SparkEMRCluster.MasterPublicDNS