<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>it.uniroma2.sae</groupId>
    <artifactId>flight-analysis</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.release>11</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spark.version>3.5.4</spark.version>
        <scala.compat.version>2.12</scala.compat.version>
        <jackson.version>2.15.2</jackson.version>
        <hbase.version>2.5.4</hbase.version>
        <log4j2.version>2.20.0</log4j2.version>
        <slf4j.version>2.0.7</slf4j.version>

        <build.file.name>flight-analysis.jar</build.file.name>
        <build.file.path>${project.build.directory}\${build.file.name}</build.file.path>

        <container.hdfs.master>hdfs-master</container.hdfs.master>
        <container.spark.master>spark-master</container.spark.master>

        <hdfs.host>hdfs-master.flight-analysis.local</hdfs.host>
        <hdfs.port>54310</hdfs.port>
        <hdfs.uri>hdfs://${hdfs.host}:${hdfs.port}</hdfs.uri>
        <hdfs.jar.path.local>${build.file.path}</hdfs.jar.path.local>
        <hdfs.jar.path.stage>/home/${build.file.name}</hdfs.jar.path.stage>
        <hdfs.jar.path.remote>/bin/${build.file.name}</hdfs.jar.path.remote>

        <spark.host>spark-master.flight-analysis.local</spark.host>
        <spark.port>7077</spark.port>
        <spark.uri>spark://${spark.host}:${spark.port}</spark.uri>
        <spark.jar.name>flight-analysis.jar</spark.jar.name>
        <spark.jar.path>/opt/spark/jars/${build.file.name}</spark.jar.path>

        <sae.config>local-config.yml</sae.config>
    </properties>

    <dependencies>
        <!-- Spark Dependencies (PROVIDED) -->
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.compat.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.compat.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_${scala.compat.version}</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Jackson (Compile & Shaded) -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <!-- Database Drivers & Connectors -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.6.0</version>
        </dependency>
        <dependency>
            <groupId>com.redislabs</groupId>
            <artifactId>spark-redis_2.12</artifactId>
            <version>3.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.spark</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-shaded-client</artifactId>
            <version>${hbase.version}</version>
        </dependency>

        <!-- Algorithms -->
        <dependency>
            <groupId>org.apache.datasketches</groupId>
            <artifactId>datasketches-java</artifactId>
            <version>6.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.tdunning</groupId>
            <artifactId>t-digest</artifactId>
            <version>3.3</version>
        </dependency>

        <!-- Logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <version>${log4j2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j2.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>3.4.4</version>
        </dependency>

        <!-- Testing Dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.10.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.10.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.4</version>
                <configuration>
                    <argLine>
                        --add-opens=java.base/java.lang=ALL-UNNAMED
                        --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
                        --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
                        --add-opens=java.base/java.io=ALL-UNNAMED
                        --add-opens=java.base/java.net=ALL-UNNAMED
                        --add-opens=java.base/java.nio=ALL-UNNAMED
                        --add-opens=java.base/java.util=ALL-UNNAMED
                        --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
                        --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
                        --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
                        --add-opens=java.base/sun.nio.cs=ALL-UNNAMED
                        --add-opens=java.base/sun.security.action=ALL-UNNAMED
                        --add-opens=java.base/sun.util.calendar=ALL-UNNAMED
                        --add-opens=java.security/java.security=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals><goal>shade</goal></goals>
                        <configuration>
                            <shadedArtifactAttached>false</shadedArtifactAttached>
                            <outputFile>${build.file.path}</outputFile>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>META-INF/LICENSE*</exclude>
                                        <exclude>META-INF/NOTICE*</exclude>
                                        <exclude>META-INF/DEPENDENCIES</exclude>
                                        <exclude>META-INF/maven/**</exclude>
                                        <exclude>**/pom.xml</exclude>
                                        <exclude>**/pom.properties</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <relocations>
                                <relocation>
                                    <pattern>com.fasterxml.jackson</pattern>
                                    <shadedPattern>it.uniroma2.sae.shaded.jackson</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.datasketches</pattern>
                                    <shadedPattern>it.uniroma2.sae.shaded.datasketches</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.tdunning.math.stats</pattern>
                                    <shadedPattern>it.uniroma2.sae.shaded.tdigest</shadedPattern>
                                </relocation>
                            </relocations>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>it.uniroma2.sae.FlightAnalysisApp</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ApacheLicenseResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ApacheNoticeResourceTransformer">
                                    <addHeader>false</addHeader>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <!-- ========================================== -->
        <!-- UPLOAD LOCAL HDFS                          -->
        <!-- ========================================== -->
        <profile>
            <id>upload-local</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.1.1</version>
                        <executions>
                            <execution>
                                <id>docker-cp-stage</id>
                                <phase>package</phase>
                                <goals><goal>exec</goal></goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <arguments>
                                        <argument>cp</argument>
                                        <argument>${hdfs.jar.path.local}</argument>
                                        <argument>${container.hdfs.master}:${hdfs.jar.path.stage}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>docker-hdfs-rm</id>
                                <phase>package</phase>
                                <goals><goal>exec</goal></goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <successCodes>
                                        <successCode>0</successCode>
                                        <successCode>1</successCode>
                                        <successCode>255</successCode>
                                    </successCodes>
                                    <arguments>
                                        <argument>exec</argument>
                                        <argument>${container.hdfs.master}</argument>
                                        <argument>hdfs</argument>
                                        <argument>dfs</argument>
                                        <argument>-rm</argument>
                                        <argument>-f</argument>
                                        <argument>${hdfs.jar.path.remote}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>docker-hdfs-put</id>
                                <phase>package</phase>
                                <goals><goal>exec</goal></goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <arguments>
                                        <argument>exec</argument>
                                        <argument>${container.hdfs.master}</argument>
                                        <argument>hdfs</argument>
                                        <argument>dfs</argument>
                                        <argument>-put</argument>
                                        <argument>-f</argument>
                                        <argument>${hdfs.jar.path.stage}</argument>
                                        <argument>${hdfs.jar.path.remote}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- ========================================== -->
        <!-- LOCAL SUBMIT                               -->
        <!-- ========================================== -->
        <profile>
            <id>submit-local</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.1.1</version>
                        <executions>
                            <execution>
                                <id>docker-copy-jar</id>
                                <phase>package</phase>
                                <goals><goal>exec</goal></goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <arguments>
                                        <argument>cp</argument>
                                        <argument>${build.file.path}</argument>
                                        <argument>${container.spark.master}:${spark.jar.path}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>docker-spark-submit</id>
                                <phase>package</phase>
                                <goals><goal>exec</goal></goals>
                                <configuration>
                                    <executable>docker</executable>
                                    <arguments>
                                        <argument>exec</argument>
                                        <argument>${container.spark.master}</argument>
                                        <argument>/opt/spark/bin/spark-submit</argument>
                                        <argument>--master</argument>
                                        <argument>${spark.uri}</argument>
                                        <argument>--class</argument>
                                        <argument>it.uniroma2.sae.FlightAnalysisApp</argument>
                                        <argument>${spark.jar.path}</argument>
                                        <argument>--config</argument>
                                        <argument>${sae.config}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- ========================================== -->
        <!-- UPLOAD REMOTE HDFS                         -->
        <!-- ========================================== -->
        <profile>
            <id>upload-remote</id>
            <properties>
                <hdfs.host>hdfs-master-node.flight-analysis.remote</hdfs.host>
                <spark.host>spark-master-node.flight-analysis.remote</spark.host>
                <sae.config>ec2-config.yml</sae.config>
                <hdfs.uri>hdfs://${hdfs.host}:${hdfs.port}</hdfs.uri>
                <spark.uri>spark://${spark.host}:${spark.port}</spark.uri>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>3.6.1</version>
                        <executions>
                            <execution>
                                <id>copy-dependencies-remote</id>
                                <phase>package</phase>
                                <goals><goal>copy-dependencies</goal></goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/hadoop-libs</outputDirectory>
                                    <includeScope>runtime</includeScope>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>hdfs-put-remote</id>
                                <phase>package</phase>
                                <goals><goal>run</goal></goals>
                                <configuration>
                                    <target>
                                        <echo message="Generating temporary core-site.xml for REMOTE ${hdfs.host}..." />
                                        <echo file="${project.build.directory}/hadoop-libs/core-site.xml"><![CDATA[<configuration>
  <property><name>fs.defaultFS</name><value>${hdfs.uri}</value></property>
  <property><name>dfs.client.use.datanode.hostname</name><value>true</value></property>
</configuration>]]></echo>
                                        <echo message="Uploading JAR to REMOTE HDFS ${hdfs.uri}..." />
                                        <java classname="org.apache.hadoop.fs.FsShell" fork="true" failonerror="true">
                                            <classpath>
                                                <pathelement path="${project.build.directory}/hadoop-libs" />
                                                <fileset dir="${project.build.directory}/hadoop-libs"><include name="*.jar" /></fileset>
                                            </classpath>
                                            <arg value="-put" /><arg value="-f" />
                                            <arg value="${hdfs.jar.path.local}" />
                                            <arg value="${hdfs.jar.path.remote}" />
                                        </java>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <dependencies>
                <dependency>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-client</artifactId>
                    <version>3.3.4</version>
                </dependency>
            </dependencies>
        </profile>

        <!-- ========================================== -->
        <!-- REMOTE SUBMIT                              -->
        <!-- ========================================== -->
        <profile>
            <id>submit-remote</id>
            <properties>
                <hdfs.host>hdfs-master-node.flight-analysis.remote</hdfs.host>
                <spark.host>spark-master-node.flight-analysis.remote</spark.host>
                <sae.config>ec2-config.yml</sae.config>
                <hdfs.uri>hdfs://${hdfs.host}:${hdfs.port}</hdfs.uri>
                <spark.uri>spark://${spark.host}:${spark.port}</spark.uri>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.1.1</version>
                        <executions>
                            <execution>
                                <id>remote-spark-submit</id>
                                <phase>package</phase>
                                <goals><goal>exec</goal></goals>
                                <configuration>
                                    <executable>spark-submit</executable>
                                    <arguments>
                                        <argument>--master</argument>
                                        <argument>${spark.uri}</argument>
                                        <argument>--class</argument>
                                        <argument>it.uniroma2.sae.FlightAnalysisApp</argument>
                                        <argument>${hdfs.uri}${hdfs.jar.path.remote}</argument>
                                        <argument>--config</argument>
                                        <argument>${sae.config}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
