# Application configuration for Flight Analysis
appName: Flight Analysis

# Define which query to run:
# Options: monthly_performance, arrival_delay_ranking, hourly_delay_percentiles
queryToRun: monthly_performance

# Define which Spark backend API to use for the query execution
# Options: rdd, dataframe, sql
appBackend: rdd

# Cluster configuration
sparkCluster:
  master:
    hostname: spark-master
    port: 7077

# Input data configuration
input:
  type: "hdfs"  # Possible types: hdfs, local, s3
  uri: "hdfs://master:54310"
  path: "/data/conv/flights/full"
  datasetFilename: ""

# Output data configuration
#
# hdfs config
#output:
#  type: "hdfs" # Possible types: hdfs, local, s3, postgres
#  uri: "hdfs://master:54310"
#  path: "/data"
#  resultDirectory: "/res"

# Output data configuration
#
# Postgres config
output:
  type: "postgres" # Possible types: hdfs, local, s3, postgres
  hostname: "postgres"
  port: 5432
  database: "flight_db"
  user: "postgres"
  password: "postgres"
