# Application configuration for Flight Analysis
appName: Flight Analysis

# Define which query to run:
# Options: monthly_performance, arrival_delay_ranking, hourly_delay_percentiles
queryToRun: monthly_performance

# Cluster configuration
sparkCluster:
  master:
    hostname: spark-master
    port: 7077

# Input data configuration
input:
  type: "hdfs"  # Possible types: hdfs, local, s3
  uri: "hdfs://master:54310"
  path: "/data/conv"
  datasetFilename: "202501_T_ONTIME_REPORTING.parquet"

# Output data configuration
output:
  type: "hdfs" # Possible types: hdfs, local, s3
  uri: "hdfs://master:54310"
  path: "/data"
  resultDirectory: "res"
