name: flight-analytics-databases

services:
  # =================================================================
  # PERSISTENCE LAYER
  # =================================================================

  # PostgreSQL Relational Database for Final Results
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    network_mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/databases/postgres:/var/lib/postgresql/data

  # Apache HBase Columnar Database for Final Results
  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase
    hostname: hbase
    network_mode: host
    tty: true
    stdin_open: true

  # Redis Instance for Final Results
  redis-output:
    image: redis:latest
    container_name: redis-output
    hostname: redis-output
    network_mode: host
    command: redis-server

  # CockroachDB Single-Node Instance for Final Results
  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb
    hostname: cockroachdb
    network_mode: host
    command: start-single-node --insecure
    volumes:
      - ./data/databases/cockroach:/cockroach/cockroach-data
