name: sky-analytics-engine

# Base configuration for HDFS worker nodes
x-hdfs-worker-base: &hdfs-worker-base
    image: matnar/hadoop:3.3.2
    networks:
        - sae-net
    tty: true
    stdin_open: true
    command: >
        sh -c "service ssh start;
        /usr/local/hadoop/bin/hdfs datanode;
        bash"

# Base configuration for Spark worker nodes
x-spark-worker-base: &spark-worker-base
    image: apache/spark:3.5.1
    user: root
    networks:
        - sae-net
    depends_on:
        - spark-master
    # Use absolute paths and point to the master service name
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://${SPARK_MASTER_HOST}:7077
    volumes:
        - ./data:/opt/spark/data
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

services:

    # Storage Layer - HDFS
    hdfs-master:
        image: matnar/hadoop:3.3.2
        container_name: hdfs-master
        hostname: ${HDFS_NAMENODE_HOST}
        networks:
            - sae-net
        ports:
            - "${HDFS_WEB_UI_PORT}:9870" # HDFS Web UI
            - "${HDFS_NAMENODE_PORT}:54310" # HDFS RPC NameNode
        volumes:
            - ./hadoop/config/workers:/usr/local/hadoop/etc/hadoop/workers
        # this is needed to keep the container running
        environment:
            - NODE_TYPE=master
        command: >
            sh -c "service ssh start;
            if [ ! -d /tmp/hadoop-root/dfs/name ]; then
              /usr/local/hadoop/bin/hdfs namenode -format;
            fi;
            /usr/local/hadoop/sbin/start-dfs.sh;
            
            hdfs dfs -mkdir -p /data/conv;
            hdfs dfs -chmod -R 777 /data/conv;
            
            tail -f /usr/local/hadoop/logs/*.log"
        tty: true
        stdin_open: true

    hdfs-worker-1:
        <<: *hdfs-worker-base
        container_name: hdfs-worker-1
        hostname: worker-1
        depends_on:
            - hdfs-master

    hdfs-worker-2:
        <<: *hdfs-worker-base
        container_name: hdfs-worker-2
        hostname: worker-2
        depends_on:
            - hdfs-master

    # Database Layer - PostgreSQL, MongoDB, HBase
    postgres:
        image: postgres:15
        container_name: postgres
        hostname: postgres
        networks:
            - sae-net
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        networks:
            - sae-net
        ports:
            - "${MONGO_PORT}:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DB}

    hbase:
        image: harisekhon/hbase:latest
        container_name: hbase
        hostname: hbase
        networks:
            - sae-net
        ports:
            - "${HBASE_UI_PORT}:16010" # Master UI
            - "${HBASE_ZK_PORT}:2181"  # Zookeeper
            - "16000:16000"            # HBase Master RPC
            - "16020:16020"            # RegionServer RPC
            - "8765:8765"              # Phoenix Query Server

    # Object Storage Layer - MinIO
    minio:
        image: quay.io/minio/minio:latest
        container_name: minio
        hostname: minio
        networks:
            - sae-net
        ports:
            - "${MINIO_PORT}:9000"
            - "${MINIO_CONSOLE_PORT}:9001"
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        volumes:
            - ./data/minio:/data
        command: server /data --console-address ":9001"

    # Ingestion Layer - NiFi
    nifi:
        image: apache/nifi:latest
        container_name: nifi
        hostname: nifi
        networks:
            - sae-net
        ports:
            - "8443:8443" # NiFi Web UI https
            - "${NIFI_WEB_HTTP_PORT}:8081" # NiFi Web UI http
            - "8085:8085" # Port for Airflow Site-to-Site
        environment:
            - NIFI_WEB_HTTP_PORT=8081
            - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USER}
            - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
        volumes:
            - ./data/raw:/opt/nifi/nifi-current/data
            - ./data/conv:/opt/nifi/nifi-current/res
            - ./hadoop/config:/opt/nifi/nifi-current/conf/hadoop-config:ro
            - ./nifi/extensions:/opt/nifi/nifi-current/nar_extensions
        links:
            - hdfs-master:${HDFS_NAMENODE_HOST}
            - hdfs-worker-1:worker-1
            - hdfs-worker-2:worker-2

    # Processing Layer - Spark
    spark-master:
        image: apache/spark:3.5.1
        container_name: spark-master
        hostname: ${SPARK_MASTER_HOST}
        user: root
        networks:
            - sae-net
        # Use absolute paths to the binaries
        command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
        ports:
            - '${SPARK_MASTER_WEBUI_PORT}:8080' # Spark Master Web UI
            - '${SPARK_MASTER_PORT}:7077' # Spark Master Port
            - '4040:4040'
        volumes:
            - ./data:/opt/spark/data
            - ./spark:/opt/spark/scripts
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    
    spark-worker-1:
        <<: *spark-worker-base
        container_name: spark-worker-1
        hostname: spark-worker-1

    spark-worker-2:
        <<: *spark-worker-base
        container_name: spark-worker-2
        hostname: spark-worker-2

    # Visualization Layer - Redis + Grafana
    redis-metrics:
        image: redis/redis-stack:latest
        container_name: redis
        hostname: redis
        networks:
            - sae-net
        ports:
            - "${REDIS_PORT}:6379" # Redis Port
            - "${REDIS_INSIGHT_PORT}:8001" # RedisInsight Port

    redis-init:
        image: redis/redis-stack:latest
        container_name: redis-init
        networks:
            - sae-net
        depends_on:
            - redis-metrics
        command: >
            sh -c '
              sleep 5;
              redis-cli -h redis -p 6379 FT.CREATE metricsIdx ON HASH PREFIX 1 metrics:phases: SCHEMA query TAG phase TAG approach TAG duration NUMERIC timestamp NUMERIC SORTABLE || true;
              echo "Indice RediSearch configurato con successo!";
            '

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        hostname: grafana
        networks:
            - sae-net
        ports:
            - "${GRAFANA_PORT}:3000" # Grafana Web UI
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
        volumes:
            - ./grafana/datasources:/etc/grafana/provisioning/datasources
            - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
        depends_on:
            - redis-metrics
            - postgres

networks:
    sae-net:
        driver: bridge
        name: sae-net
