name: flight-analytics-master

services:

  # =================================================================
  # STORAGE LAYER
  # =================================================================

  # HDFS NameNode for Distributed File Storage
  hdfs-master:
    image: matnar/hadoop:3.3.2
    container_name: hdfs-master
    user: root
    hostname: ${HDFS_NAMENODE_HOST}
    network_mode: host
    volumes:
      - ./workers:/usr/local/hadoop/etc/hadoop/workers:ro
      - ./core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml:ro
      - ./hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml:ro
    environment:
      - NODE_TYPE=master
    command: >
      sh -c "if [ ! -d /tmp/hadoop-root/dfs/name ]; then
        /usr/local/hadoop/bin/hdfs namenode -format -force;
      fi;

      /usr/local/hadoop/bin/hdfs namenode &

      echo '[INFO] Wait for NameNode to be ready...';
      until /usr/local/hadoop/bin/hdfs dfsadmin -safemode wait; do
        echo '[INFO] NameNode non ancora pronto, riprovo tra 2 secondi...';
        sleep 2;
      done;

      echo '[INFO] NameNode ready! Creating folders...';
      /usr/local/hadoop/bin/hdfs dfs -mkdir -p /data/conv;
      /usr/local/hadoop/bin/hdfs dfs -chmod -R 777 /data/conv;
      
      /usr/local/hadoop/bin/hdfs dfs -mkdir -p /data/raw;
      /usr/local/hadoop/bin/hdfs dfs -chmod -R 777 /data/raw;

      /usr/local/hadoop/bin/hdfs dfs -mkdir -p /bin;
      /usr/local/hadoop/bin/hdfs dfs -chmod -R 777 /bin;

      echo '[INFO] HDFS Master is up and running.';
      wait"
    tty: true
    stdin_open: true

  # =================================================================
  # PROCESSING LAYER
  # =================================================================

  # Apache Spark Master Instance
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    user: root
    hostname: ${SPARK_MASTER_HOST}
    network_mode: host
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./data:/opt/spark/data
    environment:
      - SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
      - SPARK_LOCAL_HOSTNAME=${SPARK_MASTER_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
