name: flight-analytics-metrics

services:
  redis-metrics:
    image: redis/redis-stack:latest
    container_name: redis
    hostname: redis
    network_mode: host
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"

  redis-init:
    image: redis/redis-stack:latest
    container_name: redis-init
    network_mode: host
    depends_on:
      - redis-metrics
    command: >
      sh -c '
        sleep 5;
        redis-cli -h localhost -p ${REDIS_PORT} FT.CREATE phaseIdx ON HASH PREFIX 1 metrics:phases: SCHEMA query TAG approach TAG phase TAG duration NUMERIC wallclock-duration NUMERIC spark-duration NUMERIC timestamp NUMERIC SORTABLE || true;
        redis-cli -h localhost -p ${REDIS_PORT} FT.CREATE stagesIdx ON HASH PREFIX 1 metrics:stages: SCHEMA query TAG approach TAG phase TAG stageId NUMERIC duration NUMERIC gcTime NUMERIC read NUMERIC written NUMERIC shuffleRead NUMERIC shuffleWrite NUMERIC timestamp NUMERIC SORTABLE || true;
        redis-cli -h localhost -p ${REDIS_PORT} FT.CREATE executorsIdx ON HASH PREFIX 1 metrics:executors: SCHEMA query TAG approach TAG phase TAG execId TAG host TAG tasks NUMERIC runTime NUMERIC cpuTime NUMERIC gcTime NUMERIC read NUMERIC written NUMERIC shuffleRead NUMERIC shuffleWrite NUMERIC timestamp NUMERIC SORTABLE || true;
        echo "RediSearch index configured successfully!";
      '

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    network_mode: host
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
