apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:$POSTGRES_PORT
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1500
  - name: Redis
    type: redis-datasource
    uid: redis-metrics-datasource
    access: proxy
    url: redis://redis-stack:$REDIS_PORT
    editable: true
    jsonData:
      client: standalone
