apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:$POSTGRES_PORT
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1500