apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-datasource-uid
    url: postgres-databases.flight-analysis.local:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: flight_db
      sslmode: disable
      postgresVersion: 1500
  - name: CockroachDB
    type: postgres
    uid: cockroachdb-datasource-uid
    url: cockroachdb-databases.flight-analysis.local:26257
    user: root
    secureJsonData:
      password: ""
    jsonData:
      database: defaultdb
      sslmode: disable
      postgresVersion: 1000
  - name: Redis
    type: redis-datasource
    uid: redis-datasource-uid
    access: proxy
    url: redis://metrics.flight-analysis.local:6379
    editable: true
    jsonData:
      client: standalone
